name: Check Rusty Import on Windows

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: linux-x86_64
            runs-on: ubuntu-22.04
            os: linux
          - name: linux-arm64
            runs-on: ubuntu-24.04-arm
            os: linux
          - name: macos-arm64
            runs-on: macos-latest
            os: macos
          - name: macos-x86_64
            runs-on: macos-13
            os: macos
          - name: windows-x86_64
            runs-on: windows-latest
            os: windows

    name: Setup on ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runs-on }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install rusty-manga-image-translator
        run: |
          python -m pip install --upgrade pip
          pip install ^
            --extra-index-url https://frederik-uni.github.io/manga-image-translator-rust/python/wheels/simple/ ^
            rusty-manga-image-translator
        shell: cmd

      - name: Test import (should not panic)
        run: python -c "import rusty_manga_image_translator"
        shell: cmd
